### PR TITLE
V5

### PR DESCRIPTION
**Pull request by nimit85**

### CODE REVIEW

**Comment by dgleich** [comment]
Are you suggesting we should merge the v5 branch into master?

**Comment by nimit85** [comment]
Doesn't seem to be working on Mac OSX 10.10. Is there an updated version?

**Comment by dgleich** [comment]
Have you tried this?

https://dgleich.wordpress.com/2010/07/08/matlabbgl-osx-64-bit/

David

On September 30, 2015 at 7:07:34 PM, nimit85 (notifications@github.com) wrote:

Closed #16.

**Comment by nimit85** [comment]
There have been changes to XCode and the way MEX files are handled. I can use the pre-compiled code, however, I cant use compile.m, it throws the following error:

Error using mex
ld: library not found for -lmbgl-macosx-intel-64-large
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Error in compile (line 107)
     eval(mexstr);

**Comment by dgleich** [comment]
Let me take a look. We probably need new compile instructions on OSX.

David

**Pull request closed without merging**
